baseURL = 'https://farnostmenin.cz/'
languageCode = 'cs-cz'
title = 'Farnost Měnín'
uglyURLs = "false"
enableEmoji = "true"
buildFuture = "true"
[params]
    description = "Oficiální stránky Římskokatolické farnosti Měnín"
[menus]
    [[menu.main]]
        identifier = "porad-bohosluzeb"
        name = "Pořad bohoslužeb"
        url = "/porad-bohosluzeb"
        weight = "2"
    [[menu.main]]
        identifier = "aktuality"
        name = "Aktuality"
        url = "/aktuality"
        weight = "1"
    [[menu.main]]
        identifier = "vyuka-nabozenstvi"
        name = "Výuka náboženství"
        url = "/vyuka-nabozenstvi"
        weight = "4"
    [[menu.main]]
        identifier = "svatosti"
        name = "Svátosti"
        url = "/svatosti"
        weight = "5"
    [[menu.main]]
        identifier = "sluzby-ve-farnosti"
        name = "Služby ve farnosti"
        url = "/sluzby-ve-farnosti"
        weight = "6"
    [[menu.main]]
        identifier = "uzitecne-odkazy"
        name = "Užitečné odkazy"
        url = "/uzitecne-odkazy"
        weight = "7"
    [[menu.main]]
        identifier = "galerie"
        name = "Fotogalerie"
        url = "/galerie"
        weight = "3"
    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt"
        weight = "8"